
version: 2

models:
  - name: users
    description: "A Users table which stores all the data of a user"
    columns:
      - name: ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: posts
    description: "Posts table which stores all the data of a posts"
    columns:
      - name: ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: badges
    description: "Badges table which stores all the data of badges"
    columns:
      - name: ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
